/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.dialog;

import dao.InvoiceDAO;
import dao.InvoiceDetailsDAO;
import dao.PaidDAO;
import dao.ProductBatchDAO;
import dao.ProductDAO;
import dao.ShelvesDetailsDAO;
import dao.SupplierDAO;
import entity.Invoice;
import entity.InvoiceDetails;
import entity.Paid;
import entity.Product;
import entity.ProductBatch;
import entity.ShelvesDetails;
import entity.Supplier;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblWidth;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STTblWidth;
import utils.Auth;
import utils.Currency;
import utils.MsgBox;
import utils.Xdate;

/**
 *
 * @author ductr
 */
public class InvoiceDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form InvoiceDetailsDialog
     */
    DefaultTableModel model;
    InvoiceDAO dao;
    List<Product> lst;
    boolean add;
    int maHD = -1;
    int update = -1;//0 cho xac nhan , 1 xac nhan, 2 da huy

    public InvoiceDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    void init() {
        add = true;
        lst = new ArrayList<>();
        dao = new InvoiceDAO();
        model = (DefaultTableModel) tblDetails.getModel();
        setLocationRelativeTo(null);
        fillList();
        fillCbx();
        Date date = new Date();
        String sDate = Xdate.toString(date, "dd-MM-yyyy");
        txtDate.setText(sDate);
        txtID.setText("(Phiếu mới)");
        txtStaff.setText(Auth.user.getId());
        // addEvt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStaff = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxSupplier = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        cbxThanhToan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxPayment = new javax.swing.JComboBox<>();
        txtSoTienTT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtList = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtThanhToan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cbxStatus = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiếu Mua Hàng");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã Hóa Đơn:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ngày Tạo:");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhân Viên:");

        txtStaff.setEditable(false);
        txtStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhà CC:");

        cbxSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_30px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thanh Toán:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Diễn Giải:");

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        cbxThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Phương Thức TT", "Thanh toán đầy đủ", "Thanh toán một phần", "Chưa thanh toán" }));
        cbxThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThanhToanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Hình thức:");

        cbxPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Ngân hàng", "Khác" }));

        txtSoTienTT.setEditable(false);
        txtSoTienTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoTienTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoTienTTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoTienTTKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Số tiền TT:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Số tiền nợ:");

        txtNo.setEditable(false);
        txtNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(txtSoTienTT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaff)
                            .addComponent(cbxThanhToan, 0, 195, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxPayment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cbxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Done_30px.png"))); // NOI18N
        jButton2.setText("THÊM VÀO HÓA ĐƠN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_30px.png"))); // NOI18N
        jButton8.setText("SP MỚI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtList.setText("DANH MỤC SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtList)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng Tiền Hàng:");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Chiết Khấu:");

        txtCK.setEditable(false);
        txtCK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCK.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tổng Tiền Thanh Toán:");

        txtThanhToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCK, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26))
        );

        tblDetails.setBackground(new java.awt.Color(255, 204, 153));
        tblDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản Phẩm", "Đơn Vị Tính", "Số Lượng", "Đơn Giá", "Thành Tiền", "Chiết Khấu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetails.setRowHeight(30);
        tblDetails.setRowMargin(5);
        tblDetails.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDetailsPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tblDetails);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_30px.png"))); // NOI18N
        jButton3.setText("XÓA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save_30px.png"))); // NOI18N
        btnSave.setText("LƯU");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pay_30px.png"))); // NOI18N
        jButton5.setText("THANH TOÁN NỢ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print_30px.png"))); // NOI18N
        jButton6.setText("IN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh_30px.png"))); // NOI18N
        jButton7.setText("LÀM MỚI");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cbxStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ xác nhân", "Xác nhân", "Hủy bỏ" }));
        cbxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStatusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("TRẠNG THÁI ĐƠN:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(cbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        addProduct();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblDetailsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblDetailsPropertyChange
        // TODO add your handling code here:.
        if ("tableCellEditor".equals(evt.getPropertyName())) {
            if (tblDetails.isEditing()) {
            } else {
                int row = tblDetails.getSelectedRow();
                String quantity = tblDetails.getValueAt(row, 2) + "";
                if (quantity.length() == 0) {
                    tblDetails.setValueAt(1, row, 2);
                    return;
                }
                for (int i = 0; i < quantity.length(); i++) {
                    if (!Character.isDigit(quantity.charAt(i))) {
                        MsgBox.alert(null, "Nhập số");
                        tblDetails.setValueAt(1, row, 2);
                        return;
                    }
                }
                if (Integer.parseInt(quantity) <= 0) {
                    MsgBox.alert(null, ">0");
                    tblDetails.setValueAt(1, row, 2);
                    return;
                }
                double percen = 0;
                try {
                    percen = Double.parseDouble(tblDetails.getValueAt(row, 5) + "");
                    if (percen >= 100) {
                        MsgBox.alert(null, "Chiet khau nho hon 100");
                        tblDetails.setValueAt(0, row, 5);
                        return;
                    }
                } catch (NumberFormatException e) {
                    MsgBox.alert(null, "Nhap so");
                    tblDetails.setValueAt(0, row, 5);
                    return;
                }

                fillDetails();
            }
        }
    }//GEN-LAST:event_tblDetailsPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new SupplierDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            addProduct();
        }

    }//GEN-LAST:event_jList1MousePressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (!valid()) {
            return;
        }
        int status = cbxStatus.getSelectedIndex();
        if (add) {//hoa don moi
            dao.insert(getInvoice());
            maHD = dao.getLastID();
            if (status == 1) {//xac nhan
                getInvoiceDetails(dao.getLastID());
                maHD = dao.getLastID();
                add = false;
                update = cbxStatus.getSelectedIndex();
            } else {//cho xac nhan
                saveTemp(dao.getLastID());
                maHD = dao.getLastID();
                add = false;
                update = cbxStatus.getSelectedIndex();
                MsgBox.alert(null, "Thông tin hóa đơn đã được lưu");
            }
            String sprice = txtSoTienTT.getText();
            if (sprice.length() == 0) {
                sprice = "0";
            } else {
                sprice = Currency.getString(sprice);
            }
            Paid p = new Paid(dao.getLastID(),
                    Double.parseDouble(sprice), new Date(), Auth.user.getId());
            new PaidDAO().insert(p);
        } else {//cap nhat
            if (status == 0) {
                MsgBox.alert(null, "Chọn trạng thái đơn trước khi cập nhật");
                return;
            }
            updateInvoice();
        }
        MsgBox.alert(null, "Thông tin hóa đơn đã được lưu");
        setForm(dao.selectByID(maHD + ""));
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbxThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThanhToanActionPerformed
        // TODO add your handling code here:
        int i = cbxThanhToan.getSelectedIndex();
        if (i == 1) {
            txtSoTienTT.setText(txtThanhToan.getText());
            txtSoTienTT.setEditable(false);
        } else if (i == 2) {
            txtSoTienTT.setText("0");
            txtNo.setText(txtThanhToan.getText());
            txtSoTienTT.setEditable(true);
        } else if (i == 3) {
            txtSoTienTT.setText("0");
            txtNo.setText(txtThanhToan.getText());
            txtSoTienTT.setEditable(false);
        }
    }//GEN-LAST:event_cbxThanhToanActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelList = (DefaultListModel) jList1.getModel();
        new ProductDialog(null, true).setVisible(true);
        ProductDAO dao = new ProductDAO();
        fillList();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtSoTienTTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTienTTKeyTyped
        // TODO add your handling code here:
        String text;
        char k = evt.getKeyChar();
        if (!Character.isDigit(k)) {
            evt.consume();
            return;
        }
        text = txtSoTienTT.getText() + evt.getKeyChar();
        double tt = Double.parseDouble(text);
        double soTienTT = Currency.getDouble(txtThanhToan.getText());
        if (tt > soTienTT) {
            txtSoTienTT.setText(Currency.getString(txtThanhToan.getText()));
            txtNo.setText(Currency.getCurrency(0));
            evt.consume();
            return;
        }
        txtNo.setText(Currency.getCurrency(soTienTT - tt));
    }//GEN-LAST:event_txtSoTienTTKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (lst.isEmpty()) {
            return;
        }
        if (tblDetails.getSelectedRow() == -1) {
            return;
        }
        lst.remove(tblDetails.getSelectedRow());
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        model.removeRow(tblDetails.getSelectedRow());
        model.fireTableDataChanged();
        fillDetails();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        printInvoice();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cbxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusActionPerformed
        // TODO add your handling code here:
        if (add) {
            int index = cbxStatus.getSelectedIndex();
            if (index == 2) {
                MsgBox.alert(null, "Tạo hóa đơn mới không thể để trạng thái đã hủy !");
                cbxStatus.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_cbxStatusActionPerformed

    private void txtSoTienTTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTienTTKeyReleased
        // TODO add your handling code here:
        String text;
        if (evt.getKeyCode() == 8) {
            text = txtSoTienTT.getText();
            if (text.length() == 0) {
                text = "0";
                txtSoTienTT.setText(text);
            }
            double tt = Double.parseDouble(text);
            double soTienTT = Currency.getDouble(txtThanhToan.getText());
            if (tt > soTienTT) {
                txtSoTienTT.setText(Currency.getDouble(txtThanhToan.getText() + "") + "");
                txtNo.setText(Currency.getCurrency(0));
                return;
            }
            txtNo.setText(Currency.getCurrency(soTienTT - tt));
        }
    }//GEN-LAST:event_txtSoTienTTKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (maHD == -1) {
            return;
        }
        if (update != 1) {
            MsgBox.alert(null, "Hóa đơn này chưa được xác nhận");
            return;
        }
        if (Currency.getDouble(txtNo.getText()) == 0) {
            MsgBox.alert(null, "Hóa đơn này đã được thanh toán hết");
            return;
        }
        PaidJDialog pj = new PaidJDialog(null, true, Currency.getDouble(txtNo.getText()));
        pj.setVisible(true);
        double paid = pj.paid;
        if (paid == 0) {
            return;
        }
        Paid p = new Paid(maHD, paid, new Date(), Auth.user.getId());
        new PaidDAO().insert(p);
        Invoice iv = dao.selectByID(maHD + "");
        iv.setDebt(iv.getDebt() - paid);
        dao.updateDebt(iv);
        setForm(iv);
        // MsgBox.alert(null, Currency.getCurrency(paid));

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceDetailsDialog dialog = new InvoiceDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxPayment;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JComboBox<String> cbxSupplier;
    private javax.swing.JComboBox<String> cbxThanhToan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Product> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtCK;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtList;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtSoTienTT;
    private javax.swing.JTextField txtStaff;
    private javax.swing.JTextField txtThanhToan;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void fillList() {
        txtList.setText("DANH MỤC SẢN PHẨM");
        ProductDAO pdao = new ProductDAO();
        List<Product> list = pdao.selectAll();
        DefaultListModel<Product> modell = new DefaultListModel<>();
        for (int i = 0; i < list.size(); i++) {
            modell.add(i, list.get(i));
        }
        jList1.setModel(modell);
    }

    private void fillCbx() {
        SupplierDAO dao = new SupplierDAO();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxSupplier.getModel();
        model.removeAllElements();
        List<Supplier> list = dao.selectAll();
        for (Supplier p : list) {
            model.addElement(p);
        }

    }

    private Invoice getInvoice() {
        Invoice i = new Invoice();
        int status = cbxStatus.getSelectedIndex();
        i.setStatus(status);
        i.setCreateDate(new Date());
        String tongTienHoaDon = txtThanhToan.getText();
        i.setAmount(Currency.getDouble(tongTienHoaDon));
        i.setDebt(Currency.getDouble(txtNo.getText()));
        i.setDiscount(Currency.getDouble(txtCK.getText()));
        i.setNote(txtNote.getText());
        i.setPaymentMethod(cbxPayment.getSelectedItem() + "");
        i.setStaffID(txtStaff.getText());
        Supplier s = (Supplier) cbxSupplier.getSelectedItem();
        i.setSupplierID(s.getId());
        if (maHD != -1) {
            i.setId(maHD);
        }
        return i;
    }

    private void getInvoiceDetails(int invoiceID) {
        if (!valid()) {
            return;
        }
        InvoiceDetailsDAO iddao = new InvoiceDetailsDAO();
        ProductBatchDAO bdao = new ProductBatchDAO();
        tblDetails.setEnabled(true);
        ShelvesDetailsDAO sdao = new ShelvesDetailsDAO();
        for (int i = 0; i < tblDetails.getRowCount(); i++) {
            ProductBatch pb = new ProductBatch();
            String date = txtDate.getText();
            pb.setEnteredDate(Xdate.toDate(date, "dd-MM-yyyy"));
            pb.setNote("");
            double gia = Currency.getDouble(tblDetails.getValueAt(i, 3) + "");
            double price = gia - gia * Double.parseDouble(tblDetails.getValueAt(i, 5) + "") / 100;
            //pb.setPrice(Curerency.getDouble(tblDetails.getValueAt(i, 3) + ""));
            pb.setPrice(price);
            pb.setProductID(lst.get(i).getId());
            pb.setQuantity(Integer.parseInt(tblDetails.getValueAt(i, 2) + ""));
            Supplier s = (Supplier) cbxSupplier.getSelectedItem();
            pb.setSupplierID(s.getId());
            int batchId = bdao.hasBatch(pb);
            if (batchId != -1) {
                pb.setId(batchId);
                bdao.update(pb);
                sdao.updateDefault(batchId, pb.getQuantity());
            } else {
                bdao.insert(pb);
                ShelvesDetails sd = new ShelvesDetails();
                sd.setShelvesID(0);
                sd.setProductBatchID(bdao.getBatch());
                sd.setQuantity(pb.getQuantity());
                sdao.insert(sd);
            }
            InvoiceDetails iv = new InvoiceDetails();
            iv.setDiscount(Double.parseDouble(tblDetails.getValueAt(i, 5) + ""));
            iv.setInvoiceID(invoiceID);
            iv.setPrice(Currency.getDouble(tblDetails.getValueAt(i, 3) + ""));
            iv.setProductBatchID(bdao.getBatch());
            iv.setQuantity(pb.getQuantity());
            iv.setProductID(lst.get(i).getId());
            iddao.insert(iv);
        }
        tblDetails.setEnabled(false);
    }

    private void addProduct() {
        if (!add) {
            MsgBox.alert(null, "Bạn không thể thêm sản phẩm vào hóa đơn đã được lưu");
            return;
        }
        Product p = jList1.getSelectedValue();
        if (p != null) {
            DefaultListModel modelList = (DefaultListModel) jList1.getModel();
            int selectedIndex = jList1.getSelectedIndex();
            if (selectedIndex != -1) {
                modelList.remove(selectedIndex);
            }
            InvoiceDetails iv = new InvoiceDetails(p.getId());
            Object[] row = new Object[]{
                p.getName(), p.getProductUnitID(), 1, Currency.getCurrency(p.getPrice()),
                Currency.getCurrency(p.getPrice()), 0
            };
            model.addRow(row);
            lst.add(p);
            fillDetails2();
        }
    }

    private boolean valid() {
        String msg = "";
        int s = cbxThanhToan.getSelectedIndex();
        if (s == 0) {
            msg += "Chọn phương thức thanh toán";
        }
        if (msg.length() == 0) {
            return true;
        }
        MsgBox.alert(null, msg);
        return false;
    }

    private void fillDetails() {

        double sum = 0;
        double ck = 0;
        for (int i = 0; i < tblDetails.getRowCount(); i++) {
            String quantity = tblDetails.getValueAt(i, 2) + "";
            double totalPrice = Integer.parseInt(quantity)
                    * lst.get(i).getPrice();
            tblDetails.setValueAt(Currency.getCurrency(totalPrice), i, 4);
            double thanhTien = lst.get(i).getPrice()
                    * Integer.parseInt(tblDetails.getValueAt(i, 2) + "");
            sum += thanhTien;
            ck += thanhTien
                    * Double.parseDouble(tblDetails.getValueAt(i, 5) + "") / 100;
        }
        txtTotalPrice.setText(Currency.getCurrency(sum));
        txtCK.setText(Currency.getCurrency(ck));
        txtThanhToan.setText(Currency.getCurrency(sum - ck));
    }

    private void fillDetails2() {
        if (lst.size() == 1) {
            txtTotalPrice.setText(Currency.getCurrency(lst.get(0).getPrice()));
            txtThanhToan.setText(txtTotalPrice.getText());
        } else {
            double totalPrice = Currency.getDouble(txtTotalPrice.getText());
            Product p = lst.get(lst.size() - 1);
            totalPrice += p.getPrice();
            txtTotalPrice.setText(Currency.getCurrency(totalPrice));
            double ck = Currency.getDouble(txtCK.getText());
            txtThanhToan.setText(Currency.getCurrency(totalPrice - ck));
        }
        int i = cbxThanhToan.getSelectedIndex();
        switch (i) {
            case 1:
                txtSoTienTT.setText(txtThanhToan.getText());
                break;
            case 2:
                txtSoTienTT.setText("0");
                txtNo.setText(txtThanhToan.getText());
                break;
            case 3:
                txtSoTienTT.setText("0");
                txtNo.setText(txtThanhToan.getText());
                break;
        }
    }

    public void setForm(Invoice i) {
        InvoiceDetailsDAO iddao = new InvoiceDetailsDAO();
        lst = iddao.getProductByInvoiceID(i.getId());
        txtID.setText(i.getId() + "");
        maHD = i.getId();
        update = i.getStatus();
        txtStaff.setText(i.getStaffID());
        String payment = i.getPaymentMethod();
        if (payment.equalsIgnoreCase("Tiền mặt")) {
            cbxPayment.setSelectedIndex(0);
        } else if (payment.equalsIgnoreCase("Ngân hàng")) {
            cbxPayment.setSelectedIndex(1);
        } else {
            cbxPayment.setSelectedIndex(2);
        }
        txtDate.setText(Xdate.toString(i.getCreateDate(), "dd-MM-yyyy"));

        // 
        //MsgBox.alert(null, Currency.getCurrency(i.getDebt()));
        txtTotalPrice.setText(Currency.getCurrency(i.getAmount() + i.getDiscount()));
        txtCK.setText(Currency.getCurrency(i.getDiscount()));
        txtThanhToan.setText(Currency.getCurrency(i.getAmount()));
        add = false;
        double no = i.getDebt();
        if (no == 0) {
            cbxThanhToan.setSelectedIndex(1);
        } else if (no < i.getAmount()) {
            cbxThanhToan.setSelectedIndex(2);
        } else {
            cbxThanhToan.setSelectedIndex(3);
        }
        cbxStatus.setSelectedIndex(i.getStatus());
        cbxSupplier.setSelectedItem(new SupplierDAO().selectByID(i.getSupplierID() + ""));
        fillTable(i.getId());
        tblDetails.setEnabled(false);
        fillPaid(i.getId() + "");
        txtSoTienTT.setText(Currency.getCurrency(i.getAmount() - i.getDebt()));
        txtNo.setText(Currency.getCurrency(i.getDebt()));
        txtSoTienTT.setEditable(false);
        cbxPayment.setEnabled(false);
        cbxThanhToan.setEnabled(false);
        cbxSupplier.setEnabled(false);
        if (update == 1 || update == 2) {
            cbxStatus.setEnabled(false);
        }
        txtNote.setText(i.getNote());
        txtNote.setEditable(false);
    }

    private void fillTable(int id) {
        InvoiceDetailsDAO iddao = new InvoiceDetailsDAO();
        ProductDAO pdao = new ProductDAO();
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        model.setRowCount(0);
        List<InvoiceDetails> lst = iddao.selectByInvoice(id);
        for (InvoiceDetails s : lst) {
            Product p = pdao.selectByID(s.getProductID());
            Object[] row = new Object[]{
                p.getName(), p.getProductUnitID(),
                s.getQuantity(), Currency.getCurrency(s.getPrice()),
                Currency.getCurrency(s.getPrice() * s.getQuantity() - s.getDiscount()),
                s.getDiscount()
            };
            model.addRow(row);
        }
    }

    private void clearForm() {
        cbxPayment.setEnabled(true);
        cbxStatus.setEnabled(true);
        cbxSupplier.setEnabled(true);
        cbxThanhToan.setEnabled(true);
        txtID.setText("(Phiếu mới)");
        txtStaff.setText(Auth.user.getId());
        txtDate.setText(Xdate.toString(new Date(), "dd-MM-yyyy"));
        cbxSupplier.setSelectedIndex(0);
        cbxThanhToan.setSelectedIndex(0);
        cbxPayment.setSelectedIndex(0);
        txtSoTienTT.setText("");
        txtNo.setText("");
        txtNote.setText("");
        lst.clear();
        fillList();
        add = true;
        maHD = -1;
        tblDetails.setEnabled(true);
        model.setRowCount(0);
        tblDetails.setModel(model);
        txtTotalPrice.setText("");
        txtCK.setText("");
        txtThanhToan.setText("");
        update = -1;

    }

    private void printInvoice() {
        try {
            String date = txtDate.getText();
            XWPFDocument document = new XWPFDocument();
            String time = java.time.LocalDateTime.now() + "";
            time = time.replaceAll(":", "");
            String title = "hd" + time + ".docx";
            FileOutputStream o = new FileOutputStream(new File(title));

            XWPFParagraph paragraph = document.createParagraph();
            paragraph.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun paragraphOneRunOne = paragraph.createRun();
            paragraphOneRunOne.setBold(true);
            paragraphOneRunOne.setFontSize(30);
            paragraphOneRunOne.setText("HÓA ĐƠN MUA HÀNG");
            paragraphOneRunOne.addBreak();
            XWPFRun run2 = paragraph.createRun();
            run2.setText("Ngày " + date.substring(0, 2) + " Tháng " + date.substring(3, 5) + " Năm " + date.substring(6));
            run2.addBreak();

            Supplier s = (Supplier) cbxSupplier.getSelectedItem();
            XWPFParagraph paragraph2 = document.createParagraph();
            XWPFRun run3 = paragraph2.createRun();
            run3.setText("Nhà cung cấp:");
            XWPFRun run4 = paragraph2.createRun();
            run4.setText(s.getName());
            run4.setBold(true);
            run4.addBreak();

            XWPFRun run5 = paragraph2.createRun();
            run5.setText("Địa chỉ: ");
            XWPFRun run6 = paragraph2.createRun();
            run6.setText(s.getAddress());
            run6.setBold(true);
            run6.addBreak();

            XWPFRun run7 = paragraph2.createRun();
            run7.setText("Ghi chú: " + txtNote.getText());

            XWPFTable table = document.createTable();
            XWPFTableRow tableRowOne = table.getRow(0);

            CTTblWidth width = table.getCTTbl().addNewTblPr().addNewTblW();
            width.setType(STTblWidth.DXA);
            width.setW(BigInteger.valueOf(9072));

            String[] header = {"SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ", "THÀNH TIỀN", "CHIẾT KHẤU"};
            for (int i = 0; i < header.length; i++) {
                XWPFTableCell cell;
                if (i == 0) {
                    cell = tableRowOne.getCell(0);
                } else {
                    cell = tableRowOne.createCell();
                }
                cell.removeParagraph(0);
                XWPFParagraph cellPara = cell.addParagraph();
                XWPFRun cellRun = cellPara.createRun();
                cellRun.setText(header[i]);
                cell.setColor("3498db");
                cellPara.setAlignment(ParagraphAlignment.CENTER);
                cell.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);
                cellRun.setBold(true);
            }
            for (int i = 0; i < tblDetails.getRowCount(); i++) {
                XWPFTableRow tableRow = table.createRow();
                tableRow.getCell(0).setText(tblDetails.getValueAt(i, 0) + "");
                tableRow.getCell(1).setText(tblDetails.getValueAt(i, 2) + "");
                tableRow.getCell(2).setText(tblDetails.getValueAt(i, 3) + "");
                tableRow.getCell(3).setText(tblDetails.getValueAt(i, 4) + "");
                tableRow.getCell(4).setText(tblDetails.getValueAt(i, 5) + "%");
            }

            XWPFParagraph paragraph3 = document.createParagraph();
            XWPFRun run8 = paragraph3.createRun();
            run8.addBreak();
            run8.addBreak();
            run8.addBreak();
            run8.setText("Tổng tiền hàng: " + txtTotalPrice.getText());
            run8.addBreak();
            run8.setText("Số tiền chiết khấu: " + txtCK.getText());
            run8.addBreak();
            run8.setText("Tổng tiền thanh toán:" + txtThanhToan.getText());
            run8.addBreak();
            run8.addBreak();
            run8.addBreak();
            run8.addBreak();
            run8.setText("Bên giao");
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.addTab();
            run8.setText("Bên nhận");
            paragraph3.setAlignment(ParagraphAlignment.RIGHT);
            document.write(o);
            o.close();
            File file = new File(title);
            Desktop.getDesktop().open(file);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateInvoice() {
        int status = cbxStatus.getSelectedIndex();
        if (status == 1) {//xac nhan
            Invoice iv = new Invoice();
            iv.setId(maHD);
            iv.setStatus(1);
            iv.setNote(txtNote.getText() + "\n Xác nhân bởi: " + Auth.user.getName());
            dao.update(iv);
            tblDetails.setEnabled(true);
            InvoiceDetailsDAO idao = new InvoiceDetailsDAO();
            idao.delete(maHD + "");
            getInvoiceDetails(maHD);
            tblDetails.setEnabled(false);
        } else {//huy
            Invoice iv = new Invoice();
            iv.setId(maHD);
            iv.setStatus(2);
            iv.setNote(txtNote.getText() + "\n Hủy bởi: " + Auth.user.getName());
            dao.delete(iv);
        }
    }

    private void saveTemp(int invoiceID) {
        tblDetails.setEnabled(true);
        InvoiceDetailsDAO idao = new InvoiceDetailsDAO();
        for (int i = 0; i < tblDetails.getRowCount(); i++) {
            InvoiceDetails iv = new InvoiceDetails();
            iv.setDiscount(Double.parseDouble(tblDetails.getValueAt(i, 5) + ""));
            iv.setInvoiceID(invoiceID);
            iv.setPrice(Currency.getDouble(tblDetails.getValueAt(i, 3) + ""));
            iv.setQuantity(Integer.parseInt(tblDetails.getValueAt(i, 2) + ""));
            iv.setProductID(lst.get(i).getId());
            idao.insertTemp(iv);
        }
        tblDetails.setEnabled(false);
    }

    private void fillPaid(String invoiceID) {
        txtList.setText("LỊCH SỬ THANH TOÁN");
        PaidDAO pdao = new PaidDAO();
        List<Paid> list = pdao.selectByInvoice(invoiceID);
        DefaultListModel modell = (DefaultListModel) jList1.getModel();
        modell.clear();
        for (int i = 0; i < list.size(); i++) {
            modell.add(i, list.get(i));
        }

        jList1.setModel(modell);
    }
}
