/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.toolbar;

import java.util.Locale;
import java.util.ResourceBundle;
import utils.XLanguage;

/**
 *
 * @author ductr
 */
public class ToolbarPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form toolbarPanel2
     */
    String bundlePath;
    ResourceBundle resourceBundle;

    public ToolbarPanel2() {
        initComponents();
        init();
    }

    void init() {
        gBtnCategory.setName("category");
        gBtnDesk.setName("desk");
        gBtnProduct.setName("product");
        gBtnInvoice.setName("invoice");
        gBtnExport.setName("export");
        gBtnReport.setName("report");
        setLanguage();
    }

    private void setLanguage() {
        String lang = XLanguage.language;
        if (lang.equalsIgnoreCase("vi")) {
            bundlePath = "config.toolbar2-vi";
            resourceBundle = ResourceBundle.getBundle(bundlePath, new Locale("vi-VN"));
            return;
        }
        bundlePath = "config.toolbar2-en";
        resourceBundle = ResourceBundle.getBundle(bundlePath, new Locale("en-EN"));
        gBtnCategory.setText(resourceBundle.getString("gBtnCategory"));
        gBtnDesk.setText(resourceBundle.getString("gBtnDesk"));
        gBtnExport.setText(resourceBundle.getString("gBtnExport"));
        gBtnProduct.setText(resourceBundle.getString("gBtnProduct"));
        gBtnReport.setText(resourceBundle.getString("gBtnReport"));
        gBtnInvoice.setText(resourceBundle.getString("gBtnInvoice"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        gBtnDesk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        gBtnCategory = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        gBtnProduct = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        gBtnInvoice = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        gBtnExport = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        gBtnReport = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();

        jToolBar1.setRollover(true);

        gBtnDesk.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        gBtnDesk.setForeground(new java.awt.Color(255, 51, 0));
        gBtnDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/office_64px.png"))); // NOI18N
        gBtnDesk.setText("Bàn Làm Việc");
        gBtnDesk.setFocusable(false);
        gBtnDesk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnDesk.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnDesk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnDesk);
        jToolBar1.add(jSeparator1);

        gBtnCategory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnCategory.setForeground(new java.awt.Color(255, 51, 0));
        gBtnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu_64px.png"))); // NOI18N
        gBtnCategory.setText("Danh Mục");
        gBtnCategory.setFocusable(false);
        gBtnCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnCategory.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnCategory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnCategory);
        jToolBar1.add(jSeparator2);

        gBtnProduct.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnProduct.setForeground(new java.awt.Color(255, 51, 0));
        gBtnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product_64px.png"))); // NOI18N
        gBtnProduct.setText("Sản Phẩm");
        gBtnProduct.setFocusable(false);
        gBtnProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnProduct.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnProduct);
        jToolBar1.add(jSeparator3);

        gBtnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnInvoice.setForeground(new java.awt.Color(255, 51, 0));
        gBtnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/invoice_64px.png"))); // NOI18N
        gBtnInvoice.setText("Hóa Đơn");
        gBtnInvoice.setFocusable(false);
        gBtnInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnInvoice.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnInvoice);
        jToolBar1.add(jSeparator4);

        gBtnExport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnExport.setForeground(new java.awt.Color(255, 51, 0));
        gBtnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warehouse_64px.png"))); // NOI18N
        gBtnExport.setText("Xuất Kho");
        gBtnExport.setFocusable(false);
        gBtnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnExport.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnExport);
        jToolBar1.add(jSeparator5);

        gBtnReport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnReport.setForeground(new java.awt.Color(255, 51, 0));
        gBtnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Business Report_64px.png"))); // NOI18N
        gBtnReport.setText("Thống Kê");
        gBtnReport.setFocusable(false);
        gBtnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnReport.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnReport);
        jToolBar1.add(jSeparator6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton gBtnCategory;
    public javax.swing.JButton gBtnDesk;
    public javax.swing.JButton gBtnExport;
    public javax.swing.JButton gBtnInvoice;
    public javax.swing.JButton gBtnProduct;
    public javax.swing.JButton gBtnReport;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
