/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.toolbar;

/**
 *
 * @author ductr
 */
public class ToolbarPanel1 extends javax.swing.JPanel {

    /** Creates new form ToolbarPanel1 */
    public ToolbarPanel1() {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogOut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnUser = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnSetting = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();

        jToolBar1.setBackground(new java.awt.Color(255, 51, 204));
        jToolBar1.setRollover(true);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 0));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout_rounded_left_64px.png"))); // NOI18N
        btnLogOut.setText("Đăng Xuất");
        btnLogOut.setFocusable(false);
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnLogOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogOut);
        jToolBar1.add(jSeparator1);

        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 51, 0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-64.png"))); // NOI18N
        btnUser.setText("Người Dùng");
        btnUser.setFocusable(false);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnUser);
        jToolBar1.add(jSeparator2);

        btnSetting.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(255, 51, 0));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings_64px.png"))); // NOI18N
        btnSetting.setText("Thiết Lập");
        btnSetting.setFocusable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnSetting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSetting);
        jToolBar1.add(jSeparator3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogOut;
    public javax.swing.JButton btnSetting;
    public javax.swing.JButton btnUser;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        btnSetting.setName("setting");
        btnUser.setName("user");
        btnLogOut.setName("logOut");
    }

}
