/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.toolbar;

import java.util.Locale;
import java.util.ResourceBundle;
import utils.XLanguage;

/**
 *
 * @author ductr
 */
public class ToolbarPanel3 extends javax.swing.JPanel {

    /**
     * Creates new form ToolbarPanel3
     */
        String bundlePath;
    ResourceBundle resourceBundle;
    public ToolbarPanel3() {
        initComponents();
        setLanguage();
    }
        private void setLanguage() {
        String lang = XLanguage.language;
        if (lang.equalsIgnoreCase("vi")) {
            bundlePath = "config.toolbar3-vi";
            resourceBundle = ResourceBundle.getBundle(bundlePath, new Locale("vi-VN"));
            return;
        }
        bundlePath = "config.toolbar3-en";
        resourceBundle = ResourceBundle.getBundle(bundlePath, new Locale("en-EN"));
        gBtnGioiThieu.setText(resourceBundle.getString("gBtnGioiThieu"));
        gBtnHelp.setText(resourceBundle.getString("gBtnHelp"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        gBtnGioiThieu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        gBtnHelp = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();

        jToolBar1.setRollover(true);

        gBtnGioiThieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnGioiThieu.setForeground(new java.awt.Color(255, 51, 0));
        gBtnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/name_tag_64px.png"))); // NOI18N
        gBtnGioiThieu.setText("Giới Thiệu");
        gBtnGioiThieu.setFocusable(false);
        gBtnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnGioiThieu.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gBtnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBtnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(gBtnGioiThieu);
        jToolBar1.add(jSeparator1);

        gBtnHelp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gBtnHelp.setForeground(new java.awt.Color(255, 51, 0));
        gBtnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help_64px.png"))); // NOI18N
        gBtnHelp.setText("Trợ Giúp");
        gBtnHelp.setFocusable(false);
        gBtnHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gBtnHelp.setMargin(new java.awt.Insets(5, 20, 5, 20));
        gBtnHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(gBtnHelp);
        jToolBar1.add(jSeparator2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gBtnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBtnGioiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gBtnGioiThieuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gBtnGioiThieu;
    private javax.swing.JButton gBtnHelp;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
