/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.main.category;

import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ductr
 */
public class Category extends javax.swing.JPanel {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        addMouseListener();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblVendor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblGroup = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblUnit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblShelves = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hồ Sơ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 153, 102));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee_20px.png"))); // NOI18N
        lblStaff.setText("Nhân Viên");
        lblStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supplier_20px.png"))); // NOI18N
        lblSupplier.setText("Nhà Cung Cấp");
        lblSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblVendor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/package_20px.png"))); // NOI18N
        lblVendor.setText("Nhà Sản Xuất");
        lblVendor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplier)
                    .addComponent(lblVendor)
                    .addComponent(lblStaff))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff)
                .addGap(18, 18, 18)
                .addComponent(lblSupplier)
                .addGap(18, 18, 18)
                .addComponent(lblVendor)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 153, 102));

        lblGroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group_of_projects_20px.png"))); // NOI18N
        lblGroup.setText("Nhóm Sản Phẩm");
        lblGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/word_20px.png"))); // NOI18N
        lblType.setText("Loại Sản Phẩm");
        lblType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUnit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/module_20px.png"))); // NOI18N
        lblUnit.setText("Đơn Vị Tính");
        lblUnit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGroup)
                    .addComponent(lblType)
                    .addComponent(lblUnit))
                .addGap(0, 149, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGroup)
                .addGap(18, 18, 18)
                .addComponent(lblType)
                .addGap(18, 18, 18)
                .addComponent(lblUnit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 153, 102));

        lblShelves.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblShelves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/wardrobe_20px.png"))); // NOI18N
        lblShelves.setText("Kệ Hàng");
        lblShelves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblShelves)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShelves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblShelves;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblVendor;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    MouseListener ml = new MouseListener() {
        Font original;

        @Override
        public void mouseClicked(MouseEvent e) {
            String name = e.getComponent().getName();
            switch (name){
                case "staff":
                  selectPanel(new CategoryStaff());
                  break;
                case "supplier":
                  selectPanel(new CategorySupplier());
                  break;  
                case "vendor":
                   selectPanel(new CategoryVendor());
                   break;
                case "productGroup":
                    selectPanel(new CategoryProductGroup());
                    break;
                case "productType":
                    selectPanel(new CategoryProductType());
                    break;
                case "productUnit":
                    selectPanel(new CategoryProductUnit());
                    break;
                case "shelves":
                    selectPanel(new CategoryShelves());
                    break;
            }
            //selectPanel(new CategoryStaff());
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            original = e.getComponent().getFont();
            Map attributes = original.getAttributes();
            attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
            e.getComponent().setFont(original.deriveFont(attributes));

        }

        @Override
        public void mouseExited(MouseEvent e) {
            e.getComponent().setFont(original);
        }

    };

    private void addMouseListener() {
        lblStaff.setName("staff");
        lblStaff.addMouseListener(ml);
        lblSupplier.setName("supplier");
        lblSupplier.addMouseListener(ml);
        lblVendor.setName("vendor");
        lblVendor.addMouseListener(ml);
        lblGroup.setName("productGroup");
        lblGroup.addMouseListener(ml);
        lblType.setName("productType");
        lblType.addMouseListener(ml);
        lblUnit.setName("productUnit");
        lblUnit.addMouseListener(ml);
        lblShelves.setName("shelves");
        lblShelves.addMouseListener(ml);
    }
    public void selectPanel(JPanel p){
        mainPanel.removeAll();
        mainPanel.add(p);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }
}
